DROP TABLE IF EXISTS tb_pay_detail;
DROP TABLE IF EXISTS tb_pay_main;
DROP TABLE IF EXISTS tb_good;
DROP TABLE IF EXISTS tb_customer;
DROP TABLE IF EXISTS tb_employee;

CREATE TABLE tb_customer
(
  Cid VARCHAR(20) NOT NULL PRIMARY KEY,
  CcompanyName VARCHAR(30) NOT NULL,
  CcompanySName VARCHAR(10) NOT NULL,
  CcompanyAddress VARCHAR(40) NOT NULL,
  CcompanyPhone VARCHAR(15) DEFAULT NULL,
  Cemail VARCHAR(30) DEFAULT NULL,
  CName VARCHAR(10) NOT NULL,
  CtelPhone VARCHAR(11) NOT NULL,
  other VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_employee
(
  Eid VARCHAR(20) NOT NULL PRIMARY KEY,
  EName VARCHAR(10) NOT NULL,
  EPas VARCHAR(20) NOT NULL DEFAULT '000000',
  Elevel VARCHAR(2) NOT NULL DEFAULT '20',
  EtelPhone VARCHAR(11) NOT NULL,
  ESalary DECIMAL(10, 2) DEFAULT 0.00,
  other VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_good
(
  
  Gid VARCHAR(20) NOT NULL PRIMARY KEY,
  GName VARCHAR(30) NOT NULL,
  GPay DECIMAL(10, 2) NOT NULL,
  Cid VARCHAR(20) NOT NULL,
  GIntroduction VARCHAR(40) DEFAULT NULL,
  other VARCHAR(20) DEFAULT NULL,
  CONSTRAINT fk_good_customer FOREIGN KEY (Cid) REFERENCES tb_customer(Cid),
  INDEX idx_good_cid (Cid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_pay_main
(
  Pid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Eid VARCHAR(20) NOT NULL,
  Pcount INT NOT NULL DEFAULT 0,
  Ptotal DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  Pdate VARCHAR(8) NOT NULL,
  other VARCHAR(20) DEFAULT NULL,
  CONSTRAINT fk_pay_main_employee FOREIGN KEY (Eid) REFERENCES tb_employee(Eid),
  INDEX idx_pay_main_eid (Eid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_pay_detail
(
  PDid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Pid INT NOT NULL,
  Gid VARCHAR(20) NOT NULL,
  Pcount2 INT NOT NULL,
  Gpay DECIMAL(10, 2) NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  other VARCHAR(20) DEFAULT NULL,
  CONSTRAINT fk_detail_main FOREIGN KEY (Pid) REFERENCES tb_pay_main(Pid) ON DELETE CASCADE,
  CONSTRAINT fk_detail_good FOREIGN KEY (Gid) REFERENCES tb_good(Gid),
  INDEX idx_detail_pid (Pid),
  INDEX idx_detail_gid (Gid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;